// <auto-generated />
namespace CallCenterManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CallHistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CallHistory));
        
        string IMigrationMetadata.Id
        {
            get { return "201903291119395_CallHistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
